platform: Any CPU
configuration: Debug
image: Visual Studio 2017

environment:
    TEST_DIR: tests\ThreadPool.Tests.dotnet

before_build:
    - cd "%TEST_DIR%"
    - nuget restore

build:
    project: $(TEST_DIR)\ThreadPool.Tests.sln
